#ifndef _FASTTALK_H_
#define _FASTTALK_H_

typedef enum _FEEDBACK_T_
{
	FT_UNKNOWN = 		0,
	FT_WELCOME = 		1,
	FT_SHELL_PROMPT = 	2,
	FT_TFTP_SUCCESS = 	3,
	FT_TFTP_FAIL = 		4,
	FT_MMC_WRITE_SUCCESS = 	5,
	FT_MMC_WRITE_FAIL = 	6,
}FEEDBACK_T;

typedef enum _COMMAND_T_
{
	CT_CTRL_C = 0,
	CT_TFTP_PA,
	CT_WRITE_PA_0,
	CT_WRITE_PA_1,
	CT_WRITE_PA_2,
	CT_WRITE_PA_3,
	CT_TFTP_PB,
	CT_WRITE_PB_0,
	CT_WRITE_PB_1,
	CT_WRITE_PB_2,
	CT_WRITE_PB_3,
	CT_TFTP_PC,
	CT_WRITE_PC_0,
	CT_WRITE_PC_1,
	CT_WRITE_PC_2,
	CT_WRITE_PC_3,
	CT_RESET,
}COMMAND_T;

typedef enum {
	STEP_BOOT,
	STEP_SHELL_START,
	STEP_TFTP_PA,
	STEP_WRITE_PA_0,
	STEP_WRITE_PA_1,
	STEP_WRITE_PA_2,
	STEP_WRITE_PA_3,
	STEP_TFTP_PB,
	STEP_WRITE_PB_0,
	STEP_WRITE_PB_1,
	STEP_WRITE_PB_2,
	STEP_WRITE_PB_3,
	STEP_TFTP_PC,
	STEP_WRITE_PC_0,
	STEP_WRITE_PC_1,
	STEP_WRITE_PC_2,
	STEP_WRITE_PC_3,
	STEP_RESET
}FASTTALK_STEP;


int fasttalk(int fd, int out, FASTTALK_STEP step, FASTTALK_STEP *new_step );
unsigned int parse_buffer(char* buf, unsigned char len, unsigned int* out);

#endif
